language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

env:
  - TYPE=coverage
  - TYPE=valgrind

addons:
  apt:
    packages:
    - lcov
    - valgrind

branches:
  only:
    - master
    - travis

before_install:
  - travis_retry gem install coveralls-lcov
  - travis_retry git clone -b autoconf https://github.com/jbboehr/shoco.git
  - ./.travis.sh before_install

install: ./.travis.sh install $TYPE
before_script: ./.travis.sh before_script $TYPE
script: ./.travis.sh script $TYPE
after_success: ./.travis.sh after_success $TYPE
after_failure: ./.travis.sh after_failure
