language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: required

dist: trusty

env:
  - TYPE=coverage
  - TYPE=valgrind

cache: false

#branches:
#  only:
#    - master
#    - travis

before_install:
  - travis_retry sudo apt-get update -y
  - travis_retry sudo apt-get install -y automake lcov pkg-config valgrind
  - travis_retry gem install coveralls-lcov
  - travis_retry git clone -b autoconf https://github.com/jbboehr/shoco.git
  - ./.travis.sh before_install

install: ./.travis.sh install $TYPE
before_script: ./.travis.sh before_script $TYPE
script: ./.travis.sh script $TYPE
after_success: ./.travis.sh after_success $TYPE
after_failure: ./.travis.sh after_failure
